apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: pingpong-log
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None 
  selector:
    app: postgres