FROM python:3.13-slim

COPY reader.py /app/reader.py
COPY requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 3002

CMD ["python", "reader.py"]
