apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: PROJECT/BACKEND_IMAGE:TAG
          ports:
            - containerPort: 5001
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: todo-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: todo-db-secret
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              value: todo-db-service
            - name: POSTGRES_PORT
              value: "5432"
