apiVersion: v1
kind: Service
metadata:
  name: todo-db-service
  namespace: todo
  labels:
    app: todo-db
spec:
  clusterIP: None
  selector:
    app: todo-db
  ports:
    - port: 5432
      targetPort: 5432