apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv
spec:
  storageClassName: shared-storage
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  local:
    path: /tmp/kube
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-my-cluster-agent-0
