apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pingpong-log

resources:
  - log-output/configmap.yaml
  - log-output/deployment.yaml
  - log-output/ingress.yaml
  - log-output/service.yaml

  - ping-pong/deployment.yaml
  - ping-pong/ingress.yaml
  - ping-pong/service.yaml
  
  - postgres/service.yaml
  - postgres/statefulset.yaml
