apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Secrets
  #- db/secret.yaml
  # github secrets now

  # Services
  - db/service.yaml
  - backend/service.yaml
  - frontend/service.yaml

  # Persistent Volume Claims
  - frontend/persistentvolumeclaim.yaml

  # StatefulSets
  - db/statefulset.yaml

  # Deployments
  - backend/deployment.yaml
  - frontend/deployment.yaml

  # Ingress
  - backend/ingress.yaml
  - frontend/ingress.yaml

  # CronJobs
  - jobs/cronjob.yaml

images:
  - name: PROJECT/BACKEND_IMAGE
    newName: gcr.io/dwk-gke-445103/todo-app-backend
    newTag: ${{ github.ref_name }}-${{ github.sha }}
  - name: PROJECT/FRONTEND_IMAGE
    newName: gcr.io/dwk-gke-445103/todo-app-frontend
    newTag: ${{ github.ref_name }}-${{ github.sha }}
  - name: PROJECT/CRONJOB_IMAGE
    newName: gcr.io/dwk-gke-445103/todo-app-cronjob
    newTag: ${{ github.ref_name }}-${{ github.sha }}


