apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-pvc
  namespace: todo
spec:
  storageClassName: todo-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
