apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: todo-frontend-hpa
  namespace: todo-main
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-app
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
